language: objective-c
osx_image: xcode9.3
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
before_install:
- pod repo update
- pod install
script:
- xcodebuild -workspace ROMPlayer.xcworkspace -sdk iphonesimulator -scheme ROMPlayer -arch x86_64 ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean build
